[2024-04-16T18:00:23.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: files_ext.ext manual__2024-04-16T17:50:16.915988+00:00 [queued]>
[2024-04-16T18:00:23.439+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: files_ext.ext manual__2024-04-16T17:50:16.915988+00:00 [queued]>
[2024-04-16T18:00:23.439+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-04-16T18:00:23.449+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): ext> on 2024-04-16 17:50:16.915988+00:00
[2024-04-16T18:00:23.454+0000] {standard_task_runner.py:60} INFO - Started process 1242 to run task
[2024-04-16T18:00:23.456+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'files_ext', 'ext', 'manual__2024-04-16T17:50:16.915988+00:00', '--job-id', '2002', '--raw', '--subdir', 'DAGS_FOLDER/files_extraction.py', '--cfg-path', '/tmp/tmp4z0j8mj8']
[2024-04-16T18:00:23.458+0000] {standard_task_runner.py:88} INFO - Job 2002: Subtask ext
[2024-04-16T18:00:23.498+0000] {task_command.py:423} INFO - Running <TaskInstance: files_ext.ext manual__2024-04-16T17:50:16.915988+00:00 [running]> on host fdd3cfdf3f53
[2024-04-16T18:00:23.561+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='files_ext' AIRFLOW_CTX_TASK_ID='ext' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T17:50:16.915988+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T17:50:16.915988+00:00'
[2024-04-16T18:00:23.565+0000] {logging_mixin.py:188} INFO - Temporary directory created: /opt/***/dags/tmpdux_1ohx
[2024-04-16T18:00:23.565+0000] {logging_mixin.py:188} INFO - Downloading file...
[2024-04-16T18:00:23.566+0000] {s3.py:1393} INFO - Downloading source S3 file from Bucket vehicle with path orders/tolldata.tgz
[2024-04-16T18:00:23.574+0000] {base.py:83} INFO - Using connection ID 'minin_s3' for task execution.
[2024-04-16T18:00:23.575+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minin_s3', conn_type='aws') credentials retrieved from login and password.
[2024-04-16T18:00:23.654+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/files_extraction.py", line 68, in ext
    s3_hook.download_file(key="orders/tolldata.tgz", bucket_name="vehicle", local_path=local_zip_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 137, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1419, in download_file
    file = NamedTemporaryFile(dir=local_path, prefix="airflow_tmp_", delete=False)  # type: ignore
  File "/usr/local/lib/python3.8/tempfile.py", line 556, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/tmpdux_1ohx/tolldata.tgz/airflow_tmp_2iyggkpi'
[2024-04-16T18:00:23.663+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=files_ext, task_id=ext, execution_date=20240416T175016, start_date=20240416T180023, end_date=20240416T180023
[2024-04-16T18:00:23.673+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2002 for task ext ([Errno 2] No such file or directory: '/opt/airflow/dags/tmpdux_1ohx/tolldata.tgz/airflow_tmp_2iyggkpi'; 1242)
[2024-04-16T18:00:23.709+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-16T18:00:23.721+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
