[2024-04-15T12:15:47.029+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extracting_files.combine_files scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-15T12:15:47.046+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extracting_files.combine_files scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-15T12:15:47.048+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-15T12:15:47.067+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): combine_files> on 2024-04-11 00:00:00+00:00
[2024-04-15T12:15:47.077+0000] {standard_task_runner.py:60} INFO - Started process 968 to run task
[2024-04-15T12:15:47.080+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extracting_files', 'combine_files', 'scheduled__2024-04-11T00:00:00+00:00', '--job-id', '1722', '--raw', '--subdir', 'DAGS_FOLDER/files_extraction.py', '--cfg-path', '/tmp/tmp6fzciwr2']
[2024-04-15T12:15:47.083+0000] {standard_task_runner.py:88} INFO - Job 1722: Subtask combine_files
[2024-04-15T12:15:47.144+0000] {task_command.py:423} INFO - Running <TaskInstance: extracting_files.combine_files scheduled__2024-04-11T00:00:00+00:00 [running]> on host fdd3cfdf3f53
[2024-04-15T12:15:47.242+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extracting_files' AIRFLOW_CTX_TASK_ID='combine_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T00:00:00+00:00'
[2024-04-15T12:15:47.246+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-15T12:15:47.247+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cat ../destination/csv_data.csv ../destination/tsv_data.csv ../destination/txt_data.csv > ../destination/combined_data.csv']
[2024-04-15T12:15:47.276+0000] {subprocess.py:86} INFO - Output:
[2024-04-15T12:15:47.278+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: ../destination/combined_data.csv: No such file or directory
[2024-04-15T12:15:47.279+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-15T12:15:47.297+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-15T12:15:47.316+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=extracting_files, task_id=combine_files, execution_date=20240411T000000, start_date=20240415T121547, end_date=20240415T121547
[2024-04-15T12:15:47.584+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1722 for task combine_files (Bash command failed. The command returned a non-zero exit code 1.; 968)
[2024-04-15T12:15:47.615+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T12:15:47.658+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
