[2024-04-03T06:47:28.902+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T06:47:25.914998+00:00 [queued]>
[2024-04-03T06:47:28.928+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T06:47:25.914998+00:00 [queued]>
[2024-04-03T06:47:28.929+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-03T06:47:28.963+0000] {taskinstance.py:2217} INFO - Executing <Task(S3KeySensor): s1minio_sensor> on 2024-04-03 06:47:25.914998+00:00
[2024-04-03T06:47:28.976+0000] {standard_task_runner.py:60} INFO - Started process 1691 to run task
[2024-04-03T06:47:28.980+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'miniouss3dag', 's1minio_sensor', 'manual__2024-04-03T06:47:25.914998+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/minios3buc.py', '--cfg-path', '/tmp/tmplmbf2d4k']
[2024-04-03T06:47:28.982+0000] {standard_task_runner.py:88} INFO - Job 262: Subtask s1minio_sensor
[2024-04-03T06:47:29.056+0000] {task_command.py:423} INFO - Running <TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T06:47:25.914998+00:00 [running]> on host 41da1b14e620
[2024-04-03T06:47:29.207+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='miniouss3dag' AIRFLOW_CTX_TASK_ID='s1minio_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T06:47:25.914998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T06:47:25.914998+00:00'
[2024-04-03T06:47:29.211+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:47:29.230+0000] {base.py:83} INFO - Using connection ID 'minin_s3' for task execution.
[2024-04-03T06:47:29.232+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minin_s3', conn_type='aws') credentials retrieved from login and password.
[2024-04-03T06:47:29.233+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-04-03T06:47:36.562+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:47:41.594+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:47:46.610+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:47:51.627+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:47:56.644+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:48:01.661+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T06:48:01.672+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 153, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 32.462025468999855 seconds exceeds the specified timeout of 30.0.
[2024-04-03T06:48:01.687+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=miniouss3dag, task_id=s1minio_sensor, execution_date=20240403T064725, start_date=20240403T064728, end_date=20240403T064801
[2024-04-03T06:48:01.719+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 262 for task s1minio_sensor (Sensor has timed out; run duration of 32.462025468999855 seconds exceeds the specified timeout of 30.0.; 1691)
[2024-04-03T06:48:01.773+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T06:48:01.802+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
