[2024-04-03T05:14:04.834+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T05:14:03.115265+00:00 [queued]>
[2024-04-03T05:14:04.856+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T05:14:03.115265+00:00 [queued]>
[2024-04-03T05:14:04.857+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-03T05:14:04.888+0000] {taskinstance.py:2217} INFO - Executing <Task(S3KeySensor): s1minio_sensor> on 2024-04-03 05:14:03.115265+00:00
[2024-04-03T05:14:04.899+0000] {standard_task_runner.py:60} INFO - Started process 364 to run task
[2024-04-03T05:14:04.905+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'miniouss3dag', 's1minio_sensor', 'manual__2024-04-03T05:14:03.115265+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/minios3buc.py', '--cfg-path', '/tmp/tmphf2vi61y']
[2024-04-03T05:14:04.907+0000] {standard_task_runner.py:88} INFO - Job 260: Subtask s1minio_sensor
[2024-04-03T05:14:04.996+0000] {task_command.py:423} INFO - Running <TaskInstance: miniouss3dag.s1minio_sensor manual__2024-04-03T05:14:03.115265+00:00 [running]> on host 41da1b14e620
[2024-04-03T05:14:05.155+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='miniouss3dag' AIRFLOW_CTX_TASK_ID='s1minio_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T05:14:03.115265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T05:14:03.115265+00:00'
[2024-04-03T05:14:05.157+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:05.175+0000] {base.py:83} INFO - Using connection ID 'minin_s3' for task execution.
[2024-04-03T05:14:05.177+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minin_s3', conn_type='aws') credentials retrieved from login and password.
[2024-04-03T05:14:05.178+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-04-03T05:14:11.164+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:16.181+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:21.202+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:26.229+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:31.244+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:36.273+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-03T05:14:36.293+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 153, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 31.135031509999862 seconds exceeds the specified timeout of 30.0.
[2024-04-03T05:14:36.320+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=miniouss3dag, task_id=s1minio_sensor, execution_date=20240403T051403, start_date=20240403T051404, end_date=20240403T051436
[2024-04-03T05:14:36.352+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 260 for task s1minio_sensor (Sensor has timed out; run duration of 31.135031509999862 seconds exceeds the specified timeout of 30.0.; 364)
[2024-04-03T05:14:36.381+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T05:14:36.429+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
