[2024-04-15T12:25:08.233+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.download_file manual__2024-04-15T12:10:05.331246+00:00 [queued]>
[2024-04-15T12:25:08.250+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.download_file manual__2024-04-15T12:10:05.331246+00:00 [queued]>
[2024-04-15T12:25:08.250+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-04-15T12:25:08.276+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_file> on 2024-04-15 12:10:05.331246+00:00
[2024-04-15T12:25:08.291+0000] {standard_task_runner.py:60} INFO - Started process 1050 to run task
[2024-04-15T12:25:08.301+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'download_file', 'manual__2024-04-15T12:10:05.331246+00:00', '--job-id', '1737', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpqo_jjp6b']
[2024-04-15T12:25:08.306+0000] {standard_task_runner.py:88} INFO - Job 1737: Subtask download_file
[2024-04-15T12:25:08.435+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_data.download_file manual__2024-04-15T12:10:05.331246+00:00 [running]> on host fdd3cfdf3f53
[2024-04-15T12:25:08.570+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='download_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T12:10:05.331246+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T12:10:05.331246+00:00'
[2024-04-15T12:25:08.573+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-15T12:25:08.575+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -s -O /full/path/to/output/tolldata.tgz https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz']
[2024-04-15T12:25:08.611+0000] {subprocess.py:86} INFO - Output:
[2024-04-15T12:25:08.627+0000] {subprocess.py:97} INFO - Command exited with return code 3
[2024-04-15T12:25:08.649+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2024-04-15T12:25:08.656+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_data, task_id=download_file, execution_date=20240415T121005, start_date=20240415T122508, end_date=20240415T122508
[2024-04-15T12:25:09.353+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1737 for task download_file (Bash command failed. The command returned a non-zero exit code 3.; 1050)
[2024-04-15T12:25:09.413+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T12:25:09.480+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
